# This is a playbook. Each item is called a play.

---
- name: Setup MacOS dev env
  hosts: localhost
  connection: local
  # facts about hosts - required for gantsign.oh-my-zsh
  # gather_facts: false 

  tasks:
    - name: Install applications
      include_role:
        name: apps

    - name: OSX settings
      include_role:
        name: osx

    - name: Setup browser
      include_role:
        name: browser

    - name: Setup devenv
      include_role:
        name: dev
