# Master playbook

---
- name: Setup MacOS dev env
  hosts: localhost
  connection: local
  # Some roles may require this but faster startup without it
  gather_facts: false 

  tasks:
    - name: Install core applications
      include_role:
        name: apps
        apply:
          tags: core
      tags: core

    # ansible-playbook main.yml --start-at-task "OSX settings"
    - name: OSX settings
      include_role:
        name: osx
        apply:
          tags: core
      tags: core

    # ansible-playbook main.yml --start-at-task "Setup developer environment"
    - name: Setup developer environment
      include_role:
        name: dev
        apply:
          tags: dev
      tags: dev
