---
# Generate an OpenSSH keypair with the default values (4096 bits, rsa)
# Uses the openssh_keypair role
# Will not regenerate if exists by default

- name: Generate ssh keys
  block:
  - name: Github
    openssh_keypair:
      path: ~/.ssh/github
  - name: Gitlab
    openssh_keypair:
      path: ~/.ssh/gitlab
