---
- name: Install iterm2
  community.general.homebrew_cask:
    name:
      - iterm2
    state: latest

- name: Install starship
  community.general.homebrew:
    name:
      - iterm2
      - starship
    state: latest
