# Install and configure dev tools

---
- name: Install applications
  include_tasks: "{{ yml_files }}"
  loop:
    - nerdfonts.yml
    - zsh.yml
    - git.yml
    - vscode.yml

    # WIP
    # - nvim.yml

    # Deprecated
    # - oh_my_zsh.yml
  loop_control:
    loop_var: yml_files