# Nvim 
---
# pyenv install 3.7
# pyenv virtualenv 3.7 py3nvim
# pyenv activate py3nvim
# python3 -m pip install pynvim
# pyenv which python

# doesn't work fully
- name: Create venv for nvim python provider
  shell: |
    pyenv install 3.7 -s
    pyenv virtualenv 3.7 nvim37
    pyenv activate nvim37
    python3 -m pip install pynvim
    pyenv which python
  register: python_path

# let g:python3_host_prog = '/Users/brian.yeung/.pyenv/versions/nvim37/bin/python'
- name: Set python3 provider in nvim
  # debug: msg="Python path is {{python_path}}"
  shell: nvim --cmd "let g:python3_host_prog = '{{ python_path }}'"

- name: Install vim plug
  shell: > 
    "sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"

- name: Plug install
  shell: "vim +PlugInstall +qall"
