---
- name: Install
  community.general.homebrew_cask:
    name:
      - neovim
      - tmux
    state: latest

# - name: Install
#   community.general.homebrew:
#     name:
#       - 
#     state: latest