# https://github.com/gantsign/ansible-role-visual-studio-code-extensions

---
- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items:
    - vscodevim.vim
    - eamodio.gitlens
