# Apple Mac caches defaults. You may need to logout and login to apply the changes.

# - { domain: "com.apple.dock", key: "enable-spring-load-actions-on-all-items", type: "boolean", value: "{{ macos_dock.settings.spring_load }}", description: "Enable spring loading for all Dock items" }
# - { domain: "com.apple.dock", key: "expose-animation-duration", type: "float", value: "{{ macos_dock.settings.expose_animation_duration }}", description: "Speed up Mission Control animations" }
# - { domain: "com.apple.dock", key: "expose-group-by-app", type: "boolean", value: "{{ macos_dock.settings.expose_group_by_app }}", description: "Group windows by application in Mission Control (i.e. use the old Exposé behavior instead)" }
# - { domain: "com.apple.dock", key: "hide-mirror", type: "boolean", value: "{{ macos_dock.settings.transparent }}", description: "Set slightly transparent Dock" }
# - { domain: "com.apple.dock", key: "minimize-to-application", type: "boolean", value: "{{ macos_dock.settings.minimize_to_application }}", description: "Minimize windows into their application’s icon" }
# - { domain: "com.apple.dock", key: "mouse-over-hilite-stack", type: "boolean", value: "{{ macos_dock.settings.mouse_over_hilite_stack }}", description: "Enable highlight hover effect for the grid view of a stack (Dock)" }
# - { domain: "com.apple.dock", key: "mru-spaces", type: "boolean", value: "{{ macos_dock.settings.rearrange_spaces }}", description: "Don’t automatically rearrange Spaces based on most recent use" }
# - { domain: "com.apple.dock", key: "show-process-indicators", type: "boolean", value: "{{ macos_dock.settings.process_indicators }}", description: "Show indicator lights for open applications in the Dock" }
# - { domain: "com.apple.dock", key: "showhidden", type: "boolean", value: "{{ macos_dock.settings.show_hidden }}", description: "Don't make Dock icons of hidden applications translucent" }
# - { domain: "com.apple.dock", key: "tilesize", type: "integer", value: "{{ macos_dock.settings.tile_size }}", description: "Set the icon size of Dock items to 36 pixels" }
# - { domain: "com.apple.dock", key: "wvous-br-corner", type: "integer", value: "{{ macos_dock.settings.bottom_right_corner }}", description: "Bottom right screen corner" }
# - { domain: "com.apple.dock", key: "wvous-br-modifier", type: "integer", value: "{{ macos_dock.settings.bottom_right_modifier }}", description: "Bottom right screen corner modifier" }
# - { domain: "com.apple.dock", key: "wvous-tl-corner", type: "integer", value: "{{ macos_dock.settings.top_left_corner }}", description: "Top left screen corner" }
# - { domain: "com.apple.dock", key: "wvous-tl-modifier", type: "integer", value: "{{ macos_dock.settings.top_left_modifier }}", description: "Top left screen corner modifier" }
# - { domain: "com.apple.dock", key: "dashboard-in-overlay", type: "boolean", value: "{{ macos_dock.settings.dashboard_in_overlay }}", description: "Don’t show Dashboard as a Space" }
# - { domain: "com.apple.dock", key: "magnification", type: "boolean", value: "{{ macos_dock.settings.magnification }}", description: "Set Dock magnification" }

---
- name: Tilesize
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: integer
    value: 36
    state: present

- name: Autohide dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

- name: Remove autohide-delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    # A high value (e.g. 1000) will effectively prevent dock from showing automatically
    value: 0
    state: present

- name: Faster dock show animation
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0.15
    state: present

- name: Disable bounce animation for icons with notification in dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: no-bouncing
    type: bool
    value: true
    state: present

# Uses geerlingguy.mac's dock role, which wraps dockutil
- name: Rearrange dock items
  vars:
    # Use the dock label name
    dockitems_remove:
      - Launchpad
      - TV
      - Podcasts
      - 'App Store'
      - Messages
      - Safari
      - Mail
      - Maps
      - Photos
      - FaceTime
      - Contacts
      - Reminders
      - Notes
      - Music
      - News

    # Must include path
    dockitems_persist:
      - name: Calendar
        path: "/Applications/Calendar.app/"
        pos: 1
      - name: Google Chrome
        path: "/Applications/Google Chrome.app/"
        pos: 2
      - name: Visual Studio Code
        path: "/Applications/Visual Studio Code.app/"
        pos: 3
  include_role:
    name: geerlingguy.mac.dock