---
# Key table: https://developer.apple.com/library/archive/technotes/tn2450/_index.html#//apple_ref/doc/uid/DTS40017618-CH1-KEY_TABLE_USAGES
- name: Map caps lock to escape
  ansible.builtin.command: hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x700000029}]}'

# Key repeat
- name: Enable Key Repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present

- name: Decrease key repeat initial delay
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15
    state: present

- name: Decrease delay between key repeats
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
    state: present

# defaults write "Apple Global Domain" "NSAutomaticPeriodSubstitutionEnabled" '0'
- name: Disable automatic period insertion
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: NSAutomaticPeriodSubstitutionEnabled
    type: int
    value: 0
    state: present

# defaults write "Apple Global Domain" "NSAutomaticQuoteSubstitutionEnabled" '0'
# defaults write "Apple Global Domain" "NSAutomaticDashSubstitutionEnabled" '0'
- name: Disable smart quote (curly quotes)
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: NSAutomaticQuoteSubstitutionEnabled
    type: int
    value: 0
    state: present
- name: Disable smart dash (long dash instead of two short dashes)
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: NSAutomaticDashSubstitutionEnabled
    type: int
    value: 0
    state: present

# defaults write "Apple Global Domain" "NSUserDictionaryReplacementItems" '()'
- name: Clear dictionary replacements
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: NSUserDictionaryReplacementItems
    type: array
    value: []
    state: present

# defaults write "Apple Global Domain" "WebAutomaticSpellingCorrectionEnabled" '0'
# defaults write "Apple Global Domain" "NSAutomaticCapitalizationEnabled" '0'
# defaults write "Apple Global Domain" "NSAutomaticSpellingCorrectionEnabled" '0'
- name: Disable automatic spelling correction
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: WebAutomaticSpellingCorrectionEnabled
    type: int
    value: 0
    state: present
- name: Disable automatic capitalization
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: NSAutomaticCapitalizationEnabled
    type: int
    value: 0
    state: present
- name: Disable automatic spelling correction
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: NSAutomaticSpellingCorrectionEnabled
    type: int
    value: 0
    state: present
