# Apple Mac caches defaults. You may need to logout and login to apply the changes.
# You can use plistwatch (requires go) to show the plist changes

---
- name: Dock Settings
  block:
    - import_tasks: keyboard.yml
    - import_tasks: trackpad.yml
    - import_tasks: display.yml
    - import_tasks: dock.yml
    - import_tasks: menubar.yml

# - name: Dock Settings
#   include_tasks: "{{ yml_files }}"
#   loop:
#     - keyboard.yml
#     - trackpad.yml
#     - display.yml
#     - dock.yml
#     - menubar.yml
#   loop_control:
#     loop_var: yml_files
